### PR TITLE
Add third parameter on disabled range

### PR DESCRIPTION
**Pull request by croftman**
Add third parameter on disabled range to add a class on the day, can be used to have different class with different ranges

### CODE REVIEW

**Comment by KennethanCeyer** [comment]
It's so late, I am sorry about it..:sad:

This PR is started to review

If you're still focus on this, please comment below

**Comment by KennethanCeyer** [comment]
I don't understand this code.. @croftman 

`disabledRanges` is 2-dimension matrix which contains `start-date` and `end-date` as follows

```javascript
const disabledRanges = [
  [ '2018-01-02', '2019-02-04' ],
  [ '2018-02-04', '2019-01-01' ]
];
```

But you tried to access `index 2` of its variable.

It seems like nonstandard feature, I would like to know what is expected feature or purpose of this code

**Comment by croftman** [comment]
Hi @KennethanCeyer 
I would like (and it's ok for me) to add a third parameter to personnalize the class of the disabled range.
So it woul be like :
const disabledRanges = [
  [ '2018-01-02', '2019-02-04', 'orange' ],
  [ '2018-02-04', '2019-01-01', 'green']
];

**Comment by KennethanCeyer** [comment]
I think this feature uses none standard form design

First. An array represents the same type value implicitly, which means we were not supposed to do this with different meaning-type value.

Second. The design of option must be clear and intuitive, It is a good idea to assume that it is optional if you want to force a value at a particular index. In this case, however, you can not omit index 2 to use the third index.

Third. The code has a code smell, Check above code review.

Do not simply ignore the design for fast code writing and ease of use. It would be convenient, of course, to add this functionality, but because it is a very detailed option, it seems to be a separate option to specify the class for a specific date range.

It temporarily closes the PR until the code is changed.

**Pull request closed without merging**
